#
# Module manifest for module 'AzureInfraIri'
#
# Generated by: Irina Debowska
#
# Generated on: 25.01.2021
#
@{ 
    # Script module or binary module file associated with this manifest.
    RootModule = 'AzureInfraIri.psm1'
    # Version number of this module.
    ModuleVersion = '0.1'
    # Supported PSEditions
    # CompatiblePSEditions = @()
    # ID used to uniquely identify this module
    GUID = '4a640a2d-8558-4b2b-90ca-5cdc167e2a4e'
    # Author of this module
    Author = 'Irina Debowska'
    # Company or vendor of this module
    CompanyName = 'Unknown'
    # Copyright statement for this module
    Copyright = '(c) 2021 Irina Debowska. All rights reserved.'
    # Description of the functionality provided by this module
    Description = 'Module to seed basic infrastructure in Azure.'
    # Minimum version of the Windows PowerShell engine required by this module
    # PowerShellVersion = ''
    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''
    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''
    # Minimum version of Microsoft .NET Framework required by this module. This 
    prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''
    # Minimum version of the common language runtime (CLR) required by this module. This 
    prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''
    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''
    # Modules that must be imported into the global environment prior to importing this 
    module
    # RequiredModules = @()
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
    # Script files (.ps1) that are run in the caller's environment prior to importing this 
    module.
    # ScriptsToProcess = @()
    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    # Format files (.ps1xml) to be loaded when importing this module
    